description = 'Dex Translator'

dependencies {
  api project(':dex-reader')
  api project(':dex-ir')
  api project(':dex-obfuscator')
  api project(':d2j-base-cmd')
  api project(':dx')
//  compile 'org.ow2.asm:asm-debug-all:5.0.3'
  testImplementation project(':d2j-smali')
  testImplementation project(':d2j-jasmin')
  testImplementation project(':ams')
}

