plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'junit', name: 'junit', version: '4.12'
    api 'com.google.guava:guava:18.0'
    api(group: 'org.antlr', name: 'antlr-runtime', version:'3.5.2') {
        exclude(module: 'stringtemplate')
    }
}
